app:
  name: w7-chat-proxy
  debug: <%= ENV['APP_DEBUG'] %>
chat:
  access_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJjZW8xNjE2OEBxcS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZ2VvaXBfY291bnRyeSI6IlVTIn0sImh0dHBzOi8vYXBpLm9wZW5haS5jb20vYXV0aCI6eyJ1c2VyX2lkIjoidXNlci1MTjVhdUNLZGo4ZWpqZTRTY1JSbWhPZ3kifSwiaXNzIjoiaHR0cHM6Ly9hdXRoMC5vcGVuYWkuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTE2NDI4ODAzMTkxNzQzMzU2NTIyIiwiYXVkIjpbImh0dHBzOi8vYXBpLm9wZW5haS5jb20vdjEiLCJodHRwczovL29wZW5haS5vcGVuYWkuYXV0aDBhcHAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY3NjQ1NTI4NCwiZXhwIjoxNjc3NjY0ODg0LCJhenAiOiJUZEpJY2JlMTZXb1RIdE45NW55eXdoNUU0eU9vNkl0RyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgbW9kZWwucmVhZCBtb2RlbC5yZXF1ZXN0IG9yZ2FuaXphdGlvbi5yZWFkIG9mZmxpbmVfYWNjZXNzIn0.h8EMPstIeZrwQ31y3xU7YE4_Wtxj0AleFw15itVMf6m28yQ_yzTCfV8PViLJGzBC13tJ3AohfekC5ogYiOpEHAQYIqmkFGqTQaAR_42dFF81z42DetulhmemCxIlRImGCXoLaBOA6LXwfJGnNs4nK1FLRNcH7H4WBQoXgrkKqn6ldW5ZLnLuDkjJRyGNkw5VsIvIByGsOnqcjS55xoFOwr-LTuke8dkq34v37wAvgXDMivYv1_WJoJCasAv5_PncVkdc7X-nxl1S_68llfX0mrs-s7qbWkVLQ1DH7-y69bvzsh36XSBQwGy2zUb6EK6ccuVHEGRYiyGqlOAu3Fw6vA
  proxy: ""
  accept_language: en-US,en
redis:
  host: <%= ENV['REDIS_HOST'] %>
  port: <%= ENV['REDIS_PORT'] %>
  username: <%= ENV['REDIS_USERNAME'] %>
  password: <%= ENV['REDIS_PASSWORD'] %>
  database: <%= ENV['REDIS_DATABASE'] %>